stages:
  extract_market_data:
    cmd: python src/data/extract_market_data.py
    deps:
      - src/data/extract_market_data.py
    params:
      - extract_market_data
    outs:
      - data/external/apple_technical_macro_features.csv

  merge_news_1:
    cmd: python src/data/merge_news_1.py
    deps:
      - src/data/merge_news_1.py
      - data/external/apple_technical_macro_features.csv
      - data/external/apple_news_data.csv
    params:
      - merge_news_1
    outs:
      - data/interim/kaggle_technical_news.csv

  merge_news_2:
    cmd: python src/data/merge_news_2.py
    deps:
      - src/data/merge_news_2.py
      - data/interim/kaggle_technical_news.csv
      - data/external/news.csv
    params:
      - merge_news_2
    outs:
      - data/interim/kaggle_github_technical_news.csv

  merge_news_3:
    cmd: python src/data/merge_news_3.py
    deps:
      - src/data/merge_news_3.py
      - data/interim/kaggle_github_technical_news.csv
      - data/external/all_the_news_2.000.csv
      - data/external/all_the_news_2.001.csv
      - data/external/all_the_news_2.002.csv
      - data/external/all_the_news_2.003.csv
    params:
      - merge_news_3
    outs:
      - data/interim/all_news_merged_uncleaned.csv
      - data/interim/processing_checklist.json

  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - data/interim/all_news_merged_uncleaned.csv
    params:
      - data_ingestion
    outs:
      - data/raw/final_raw_dataset.csv

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/final_raw_dataset.csv
    params:
      - preprocess_data
    outs:
      - data/processed/cleaned_news_features.csv
      - data/processed/cleaning_state.json

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/processed/cleaned_news_features.csv
    params:
      - feature_engineering
    outs:
      - data/processed/final_sentiment_scored_dataset.csv