stages:
  scrape_news:
    cmd: python src/data/scrape_news.py
    deps:
      - src/data/scrape_news.py
    params:
      - scrape_news
    outs:
      - data/raw/apple_news_data.csv

  calculate_sentiment:
    cmd: python src/features/calculate_sentiment.py
    deps:
      - src/features/calculate_sentiment.py
      - data/raw/apple_news_data.csv
    params:
      - calculate_sentiment
    outs:
      - data/processed/apple_news_sentiment.csv

  build_datasets:
    cmd: python src/data/build_datasets.py
    deps:
      - src/data/build_datasets.py
      - data/processed/apple_news_sentiment.csv
    params:
      - build_datasets
    outs:
      - data/processed/dataset_small.csv
      - data/processed/dataset_large.csv